version: '3.8'

services:

  eureka:
    image: felsam99/eurekaserveur:1.0.0
    container_name: eureka
    ports:
      - "8761:8761"
    depends_on:
      - db
    networks:
      - backend

  gestionuser-service:
    image: felsam99/sparingconnect_gestionutilisateur:1.1.0
    container_name: gestionuser-service-1
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8081:8081"
    depends_on:
      - eureka
      - db
    networks:
      - backend

  gestionprofil-service:
    image: felsam99/sparingconnect_gestionprofil:1.0.6
    container_name: gestionprofil-service-2
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8082:8082"
    depends_on:
      - eureka
      - db
    networks:
      - backend

  gestionmessage-service:
    image: felsam99/sparingconnect_gestiomessage:1.0.2
    container_name: gestionmessage-service-3
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    ports:
      - "8083:8083"
    depends_on:
      - eureka
      - db
    networks:
      - backend

  db:
    image: postgres:13
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5433:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  db-data:
    driver: local